Atividade 1:

Crie um array unidimencional com os numeros de 1 a 12. Transforme este array em uma matriz de 3 linhas e 4 colunas.

(DESAFIO: Aplique a transposição da matriz para criar as dimensões em 4x3 (.transpose) e, em seguida, crie um array unidimensional (.flatton)).

In [1]:
import numpy as np

# Array unidimensional
array_1d = np.arange(1, 13)
print("Array Unidimensional:")
print(array_1d)



Array Unidimensional:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
# Matriz de 3x4
matriz_3x4 = array_1d.reshape(3, 4)
print("\nMatriz 3x4:")
print(matriz_3x4)



Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# Transposição da matriz
matriz_4x3 = matriz_3x4.T
print("\nMatriz Transposta 4x3:")
print(matriz_4x3)



Matriz Transposta 4x3:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [4]:
# Array unidimensional a partir da matriz transposta
array_flat = matriz_4x3.flatten()
print("\nArray Unidimensional a partir da Matriz Transposta:")
print(array_flat)



Array Unidimensional a partir da Matriz Transposta:
[ 1  5  9  2  6 10  3  7 11  4  8 12]


ATIVIDADE 2:

LEIA O ARQUIVO cLASSIDISCO.CSV TRABALHADO EM AULA ANTERIORES E APLIQUE O COMANDO .DESCRIBE() PARA GERAR UM INDISE ESTATISTICA PREVIS DE DADOS. NÃO ESQUEÇA DOS COMANDOS PARA VERIFICAR AS PRIMEIRAS E ULTIMAS LINHAS DO DATASET COMO APOIO NESSA ACTIVIDADE.